language: cpp

os:
- linux
- osx
- windows

addons:
  apt:
    packages:
    - rpm

compiler:
- gcc

script:
- cmake -H. -B./build
- cmake --build ./build
- cd ./build
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then cpack -G TGZ && cpack -G DEB && cpack -G RPM; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then cpack -G DragNDrop; fi
- rm -rf ./cpack/_CPack_Packages

build_script:
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then cpack -G WIX; fi

deploy:
  provider: releases
  user: lozchkavarene
  password:
    secure: DLsT9/aVPdOVOcbEp8AEBjW7vlzG01UnNCAwxzKcuEVEdyowpYWqkaURSQqGtrCD/NvmOSKX2PrCl/yKh4nqPGiVmR6XTutluOkWA3q7lPy6sbthMKSrAFE08+4j+YrFzTRo8ybKyHm22SFd3QYM1WTc0WL0KMqroPlkXwYv/JteOkbBkKu5dmmQADHW78vkP3BXScngoaUNas4VAr9HxjQrUT3vKiZqgvkdmEPjrVm3UpZ7GGw1ToaUSCxbYnt3n/7X/wR2AAH3TgCtXaFtR2fi+9KR9JpKU6gN4MOS8VoaC2NNBoLO8cI3/YjJBLYnC1gdWzJ4CKFfKgLOvbSKm5zSpnFagustKsv4hmuBy3I1w0USHLkQb3rx1YVwF9dzfIzZ/21o9PVuHPHm3iRbbRMz9Vq1cSF2mNmlQzn41etdqHL6vnD7A/N/8YawIkyVZbWis0wXp5Jp3S/RllmSWnKIpBddu8ZMFdQ3b1zrT5/uMmyo1GkNN4LqKkBqdb4F1jnJ+KYoxfUgyK+IMBAj+/AXPuKk4xKYHJSZPKdm1RGteVgnkLmREWUwvGPVLHcuIhMGgcfpvr3Czuh7cT1d/oGQiZNG076tHxvyBn0r2b3HzpmlfLf/TiIzFQnivCPQDm4Ri2ZmorD+JNod2VYur21JHT7VtLJuWSmwqBN1Y3A=
  file_glob: true
  file: cpack/*
  skip_cleanup: true
  on:
    tags: true
